version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
     - db-data:/var/lib/postgresql/data
    restart: always

  rust:
    image: gcr.io/crypto-isotope-229419/reminders-rust
    restart: always
    depends_on:
     - db

  nginx:
    image: gcr.io/crypto-isotope-229419/reminders-nginx
    ports:
     - "80:80"
     - "443:443"
    restart: always

  backup:
    image: gcr.io/crypto-isotope-229419/reminders-backup
    restart: always
    depends_on:
      - db

volumes:
  db-data:
    driver: local

