version: '3'
services:
  db:
    image: postgres:alpine
    volumes:
     - db-data:/var/lib/postgresql/data

  rust:
    image: reminders-rust

  nginx:
    image: nginx-dev
    ports:
     - "80:80"
     - "443:443"

volumes:
  db-data:
    driver: local
